<?php
/**
 * Implements hook_block_info().
 *
 */
function vc_footer_block_block_info() {
 
  $blocks['vc_footer_block'] = array(
    'info' => t('Coppy right'),
    'status' => TRUE,
    'region' => 'footer',  // Not usually provided.
  );
 return $blocks;
}

/**
 * Implements hook_block_configure().
 *
 * This hook declares configuration options for blocks provided by this module.
 */
function vc_footer_block_block_configure($delta = '') {
  $form = array();
  if ($delta == 'vc_footer_block') {
    $form['vc_footer_block_form'] = array(
      '#type' => 'textfield',
      '#title' => t('Block contents'),
      '#size' => 60,
      '#description' => t('This text will appear in footer.'),
        '#default_value' => variable_get('vc_footer_block_string',  t("© 2012 Hopkinton's Television Station")),
    );
  }
  return $form;
}


/**
 * Implements hook_block_save().
 */
function vc_footer_block_block_save($delta = '', $edit = array()) {
  if ($delta == 'vc_footer_block') {
    variable_set('vc_footer_block_string', $edit['vc_footer_block_form']);
  }
  return;
}

/**
 * Implements hook_block_view().
 *
 * This hook generates the contents of the blocks themselves.
 */
function vc_footer_block_block_view($delta = '') {
  if ($delta == 'vc_footer_block') {
    $block['subject'] = '<none>';
    $block['content'] = array('#markup' => variable_get('vc_footer_block_string', t("© 2012 Hopkinton/'s Television Station")));
  }
  return $block;
}